### ISSUE TITLE
Setup cron jobs to restart the service in order to be more reliable

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/searx_ynh#105]
I have tested our search.trom.tf instance and from time to time it will not showcase more than 1 result. Restarting it with `systemctl restart uwsgi-app@searx` will make it work again. I suggest ynh to add a cron job for daily restarts.

**Comment by tio-trom** [comment]
So I tested this and works a lot better. I have added a cron `*/40 * * * * sudo systemctl restart uwsgi-app@searx` to restart every 40 minutes. Probably it should be fine to restart every day or so. But so far it makes a huge difference and our searx instance always seems to work.

**Comment by yalh76** [comment]
have you tried with last version ?
