### ISSUE TITLE
Marked as broken?

### ISSUE THREAD

**Issue by bigjdunham** [YunoHost-Apps/searx_ynh#106]
I keep getting a message from my yunohost server that the Searx app has been marked as broken, but I don't see any evidence as to why? The Searx app still works from my end, so I'm not sure why it's marked as broken. Any enlightenment on this issue would be very helpful. Thanks.

**Comment by prog-amateur2** [comment]
Hello, I would like to confirm the same issue as @bigjdunham. Please, feel free to provide explanation, at least just for information. Thank you very much for your kind feedback.

**Comment by tio-trom** [comment]
Same here I was wondering. Thanks!

**Comment by tootbrute** [comment]
I just installed the app but it gives me an "Internal Server Error".

Maybe new installations are broken?

**Comment by yalh76** [comment]
app is back working since 1th april
