### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/searx_ynh#22]
hi, 
i had searx working few months ago, and it was broke in june and auto-deleted, and never could reinstall it working...
i found now a bit of time to try a reinstall, 
but install fails : 

yunohost -v

> yunohost: 2.7.2
> yunohost-admin: 2.7.2
> moulinette: 2.7.2
> ssowat: 2.7.2

there are the install logs just before the error (i hope there are the good lines) : 

> ...
> 2017-12-01 00:38:57,445 INFO     yunohost.hook <lambda> - [1664.1] + ynh_replace_string __FINALPATH__ /opt/yunohost/searx /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 00:38:57,445 INFO     yunohost.hook <lambda> - [1664.1] + delimit=@
> 2017-12-01 00:38:57,445 INFO     yunohost.hook <lambda> - [1664.1] + match_string=__FINALPATH__
> 2017-12-01 00:38:57,445 INFO     yunohost.hook <lambda> - [1664.1] + replace_string=/opt/yunohost/searx
> 2017-12-01 00:38:57,446 INFO     yunohost.hook <lambda> - [1664.1] + workfile=/etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 00:38:57,446 INFO     yunohost.hook <lambda> - [1664.1] + sudo sed --in-place s@__FINALPATH__@/opt/yunohost/searx@g /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 00:38:57,459 INFO     yunohost.hook <lambda> - [1664.1] + ynh_store_file_checksum /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 00:38:57,459 INFO     yunohost.hook <lambda> - [1664.1] + local checksum_setting_name=checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf
> 2017-12-01 00:38:57,459 INFO     yunohost.hook <lambda> - [1664.1] ++ sudo md5sum /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 00:38:57,460 INFO     yunohost.hook <lambda> - [1664.1] ++ cut '-d ' -f1
> 2017-12-01 00:38:57,473 INFO     yunohost.hook <lambda> - [1664.1] + ynh_app_setting_set searx checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf 89bee66755cf9d0b0ac362bb888ecdca
> 2017-12-01 00:38:57,473 INFO     yunohost.hook <lambda> - [1664.1] + sudo yunohost app setting searx checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf -v 89bee66755cf9d0b0ac362bb888ecdca --quiet
> 2017-12-01 00:38:57,738 INFO     moulinette.actionsmap process - processing action [1958.1]: yunohost.app.setting
> 2017-12-01 00:38:57,766 INFO     yunohost.hook <lambda> - [1664.1] + sudo systemctl reload nginx
> 2017-12-01 00:38:57,821 WARNING  yunohost.hook <lambda> - [1664.1] Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
> 2017-12-01 00:38:57,825 INFO     yunohost.hook <lambda> - [1664.1] + ynh_exit_properly
> 2017-12-01 00:38:57,825 INFO     yunohost.hook <lambda> - [1664.1] + exit_code=1
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + '[' 1 -eq 0 ']'
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + trap '' EXIT
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + set +eu
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + echo -e '!!\n  searx'\''s script has encountered an error. Its execution was cancelled.\n!!'
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + type -t ynh_clean_setup
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + ynh_die
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + echo ''
> 2017-12-01 00:38:57,827 INFO     yunohost.hook <lambda> - [1664.1] + exit 1
> 2017-12-01 00:38:57,825 WARNING  yunohost.hook <lambda> - [1664.1] !!
> 2017-12-01 00:38:57,827 WARNING  yunohost.hook <lambda> - [1664.1]   searx's script has encountered an error. Its execution was cancelled.
> 2017-12-01 00:38:57,828 WARNING  yunohost.hook <lambda> - [1664.1] !!
> ...

thx for your help ;)

**Comment by maniackcrudelis** [comment]
Hi isAAAc

please try the testing branch instead
```
sudo yunohost app install https://github.com/YunoHost-Apps/searx_ynh/tree/testing --verbose
```
It should works, we know the stable branch doesn't work, and we found the problem.
We're going to merge as soon as possible.

**Comment by isAAAc** [comment]
it doesn't work neither : 

> 
> 2017-12-01 01:01:21,743 INFO     yunohost.hook <lambda> - [5929.1] + sudo sed --in-place s@__FINALPATH__@/opt/yunohost/searx@g /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 01:01:21,755 INFO     yunohost.hook <lambda> - [5929.1] + ynh_store_file_checksum /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 01:01:21,755 INFO     yunohost.hook <lambda> - [5929.1] + local checksum_setting_name=checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf
> 2017-12-01 01:01:21,756 INFO     yunohost.hook <lambda> - [5929.1] ++ sudo md5sum /etc/nginx/conf.d/krashboyz.org.d/searx.conf
> 2017-12-01 01:01:21,756 INFO     yunohost.hook <lambda> - [5929.1] ++ cut '-d ' -f1
> 2017-12-01 01:01:21,770 INFO     yunohost.hook <lambda> - [5929.1] + ynh_app_setting_set searx checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf 89bee66755cf9d0b0ac362bb888ecdca
> 2017-12-01 01:01:21,770 INFO     yunohost.hook <lambda> - [5929.1] + sudo yunohost app setting searx checksum__etc_nginx_conf.d_krashboyz.org.d_searx.conf -v 89bee66755cf9d0b0ac362bb888ecdca --quiet
> 2017-12-01 01:01:22,035 INFO     moulinette.actionsmap process - processing action [6213.1]: yunohost.app.setting
> 2017-12-01 01:01:22,064 INFO     yunohost.hook <lambda> - [5929.1] + sudo systemctl reload nginx
> 2017-12-01 01:01:22,115 WARNING  yunohost.hook <lambda> - [5929.1] Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
> 2017-12-01 01:01:22,118 INFO     yunohost.hook <lambda> - [5929.1] + ynh_exit_properly
> 2017-12-01 01:01:22,118 INFO     yunohost.hook <lambda> - [5929.1] + exit_code=1
> 2017-12-01 01:01:22,118 WARNING  yunohost.hook <lambda> - [5929.1] !!
> 2017-12-01 01:01:22,118 INFO     yunohost.hook <lambda> - [5929.1] + '[' 1 -eq 0 ']'
> 2017-12-01 01:01:22,118 WARNING  yunohost.hook <lambda> - [5929.1]   searx's script has encountered an error. Its execution was cancelled.
> 2017-12-01 01:01:22,119 INFO     yunohost.hook <lambda> - [5929.1] + trap '' EXIT

not sure about the journalctl -xn output , but i think there are those lines (gnusocial is very verbose at the same moment) : 

> déc. 01 01:01:22 krashboyz sudo[6216]: root : TTY=pts/1 ; PWD=/var/cache/yunohost/from_file/searx_ynh-testing/scripts ; USER=root ; COMMAND=/bin/systemctl reload nginx
> déc. 01 01:01:22 krashboyz systemd[1]: Reloading A high performance web server and a reverse proxy server.
> déc. 01 01:01:22 krashboyz systemd[1]: nginx.service: control process exited, code=exited status=1
> déc. 01 01:01:22 krashboyz systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
> déc. 01 01:01:22 krashboyz nginx[6219]: nginx: [emerg] "sub_filter" directive is duplicate in /etc/nginx/conf.d/yunohost_panel.conf.inc:2
> déc. 01 01:01:22 krashboyz sudo[6216]: pam_unix(sudo:session): session closed for user root
> déc. 01 01:01:22 krashboyz sudo[6230]: root : TTY=pts/1 ; PWD=/var/cache/yunohost/from_file/searx_ynh-testing/scripts ; USER=root ; COMMAND=/usr/bin/yunohost app setting searx domain --output-as plain --quiet
> déc. 01 01:01:23 krashboyz sudo[6279]: root : TTY=pts/1 ; PWD=/var/cache/yunohost/from_file/searx_ynh-testing/scripts ; USER=root ; COMMAND=/usr/bin/apt-get -y -qq autoremove --purge searx-ynh-deps

do you prefer i wait the next merge to continue the investigation ?

**Comment by maniackcrudelis** [comment]
Does your nginx reload properly after removing searx?
You can have a look at /var/log/nginx/error.log to find more information about the failing of nginx.

It seems weird to me that would be linked to searx.

**Comment by isAAAc** [comment]
/var/log/nginx/error.log

> 2017/12/01 01:01:22 [emerg] 6219#0: "sub_filter" directive is duplicate in /etc/nginx/conf.d/yunohost_panel.conf.inc:2
> 2017/12/01 01:01:26 [notice] 6455#0: signal process started

yep i don't understand what's the problem

**Comment by JimboJoe** [comment]
Can you please tell what this command returns?
```
grep -R sub_filter /etc/nginx/conf.d/
```

**Comment by isAAAc** [comment]
grep -R sub_filter /etc/nginx/conf.d/

> /etc/nginx/conf.d/yunohost_panel.conf.inc:sub_filter </head> '<script type="text/javascript" src="/ynhpanel.js"></script></head>';
> /etc/nginx/conf.d/yunohost_panel.conf.inc:sub_filter_once on;
> /etc/nginx/conf.d/yunohost_panel.conf.inc:sub_filter_types application/xhtml+xml;

**Comment by JimboJoe** [comment]
what about `grep -R 'yunohost_panel' /etc/nginx/` ?

**Comment by isAAAc** [comment]
grep -R 'yunohost_panel' /etc/nginx/

> /etc/nginx/conf.d/soc.krashboyz.org.d/hubzilla.conf-back-20170210-20-07:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/port.krashboyz.org.d/wordpress__2.conf:  #--PRIVATE--include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/wallabag2.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/sogo.conf.save:        include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/flarum.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/radicale.conf:        include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/opensondage.conf:     include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/zerobin.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/jirafeau.conf:        include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/nextcloud.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/kanboard.conf:        include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/wordpress.conf:  #--PRIVATE--include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/linuxdash.conf:       include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/garradin.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/phpldapadmin.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/jappix.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/dokuwiki.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/movim.conf:include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/roundcube.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/krashboyz.org.d/phpmyadmin.conf:  include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/stream.krashboyz.org.d/my_webapp.conf:    include conf.d/yunohost_panel.conf.inc;
> /etc/nginx/conf.d/pic.krashboyz.org.d/lutim.conf:    include conf.d/yunohost_panel.conf.inc;

**Comment by JimboJoe** [comment]
Hm... why doesn't `searx.conf` appear?

**Comment by isAAAc** [comment]
^^ perhaps because as said in the title : it is not installed, i can't install it anymore, that 's the problem 💃

**Comment by isAAAc** [comment]
well, 
i installed it to an new domain, install ok
i think we can close this issue, it will stay a mystery ,  ghost in the shell ;)

**Comment by Josue-T** [comment]
> i installed it to an new domain, install ok

Ok, was it in the same yunohost instance ?

**Comment by isAAAc** [comment]
> Ok, was it in the same yunohost instance ?

yep
