### ISSUE TITLE
Stretch: dependency python-pybabel is not available

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/searx_ynh#27]
On Stretch, searx is currently not installable because python-pybabel is not available : 

>Package python-pybabel is not available, but is referred to by another package.
>This may mean that the package is missing, has been obsoleted, or
>is only available from another source

A quick and dirty test was to remove this dependency, and then I was able to have a successful install, though I didn't check if the app was still functional.

**Comment by trillerpfeife** [comment]
python-babel is present instead. python-pybabel is just a transitional package for python-babel.
I tested the app by changing the dependency and it worked out!
