### ISSUE TITLE
Upgrade from 13.1 to 14.0 fails

### ISSUE THREAD

**Issue by razzor1984** [YunoHost-Apps/searx_ynh#39]
Hello, i did - sudo yunohost app upgrade searx -u https://github.com/YunoHost-Apps/searx_ynh/tree/testing --verbose   --- Via SSH and ran into an error:

`+ pip install -U setuptools
Warning: Traceback (most recent call last):
Warning:   File "/opt/yunohost/searx/bin/pip", line 7, in <module>
Warning:     from pip import main
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/__init__.py", line 76, in <module>
Warning:     from pip.commands import commands, get_summaries, get_similar_commands
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/commands/__init__.py", line 6, in <module>
Warning:     from pip.commands.bundle import BundleCommand
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>
Warning:     from pip.commands.install import InstallCommand
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>
Warning:     from pip.req import InstallRequirement, RequirementSet, parse_requirements
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
Warning:     from .req_install import InstallRequirement
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/req/req_install.py", line 42, in <module>
Warning:     from pip.utils.hashes import Hashes
Warning:   File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/utils/hashes.py", line 5, in <module>
Warning:     from pip.exceptions import HashMismatch, HashMissing, InstallationError
Warning: ImportError: cannot import name HashMissing
+ ynh_exit_properly
+ local exit_code=1
+ '[' 1 -eq 0 ']'
+ trap '' EXIT
+ set +eu
+ echo -e '!!\n  searx'\''s script has encountered an error. Its execution was cancelled.\n!!'
+ type -t ynh_clean_setup
Warning: !!
Warning:   searx's script has encountered an error. Its execution was cancelled.
Warning: !!`

Is the python package still the buggy?
best regards razzor

**Comment by AkselRocks** [comment]
https://github.com/razzor1984 can this be closed?

**Comment by razzor1984** [comment]
@AkselRocks  yep - the updated script is now working

**Comment by AkselRocks** [comment]
@razzor1984 then close it please.
