### ISSUE TITLE
Integrate latest Pulls

### ISSUE THREAD

**Issue by HyperCriSiS** [YunoHost-Apps/searx_ynh#50]
Hi,

would it be possible that you make an update with latest Searx pulls?
I use searx with configuration in the URL and because of a bug it does not work properly.
It seems to be fixed with PR: https://github.com/asciimoo/searx/pull/1599

Thanks and regards,
Hyper

**Comment by maniackcrudelis** [comment]
Hello HyperCriSiS
We can't update the app from a non validated pull request.
As soon as this PR will be merged and a release made, the package will be updated.

If you need for your own usage this fix, you can either patch your searx instance with the diff of the PR, which is quite simple https://github.com/asciimoo/searx/pull/1599/files#diff-4d31efe5636b3c9b3fd0224816b6bc13 or update the package to install from this branch on your side.

**Comment by HyperCriSiS** [comment]
Hi,

ok, thanks for the information. Can I just edit the files with the changes?

Thanks,
Hyper

**Comment by maniackcrudelis** [comment]
As the line 295 of this file is 2 years old. Yes you could probably just edit the file to make it works.
However, an upgrade of the package will overwrite your changes.

**Comment by HyperCriSiS** [comment]
Will there be an update to 0.15.0 soon?

**Comment by maniackcrudelis** [comment]
The work is still in progress https://github.com/YunoHost-Apps/searx_ynh/pull/41
