### ISSUE TITLE
image search: unexpected crash

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/searx_ynh#51]
When searching for images:
google images (unexpected crash: No JSON object could be decoded), bing images (unexpected crash: expected string or buffer), 500px (unexpected crash: 'photos')

**Comment by AkselRocks** [comment]
Work around:
Copy a newer searx folder from github:

- become root: su
- download the new files: git clone https://github.com/asciimoo/searx.git
- make a backup of exstisting searx: cp -aR /opt/yunohost/searx/. /opt/yunohost/searx.014yuno
- copy the related new files: cp -aR ./searx/searx/. /opt/yunohost/searx/searx/
- set the permissions: chown -R searx:searx /opt/yunohost/searx/
- delete downloaded files: rm -R ./searx

Works for me.
Did I miss something? 

Maybe someone can put this into a yunohost update script.

**Comment by maniackcrudelis** [comment]
By doing a git clone from the official repo, you have upgraded your searx to 0.15.0
A PR needs some love for this upgrade, https://github.com/YunoHost-Apps/searx_ynh/pull/41

**Comment by AkselRocks** [comment]
- It is not a complete clone (which does not work), but only the searx folder within the (root)searx folder. But it solves my image search issues.
- And it is not an upgrade to Python3.

So its not really an (clean) upgrade. Just a workaround ...

**Comment by AkselRocks** [comment]
It is not a complete clone (which does not work), but only the searx folder within the (root)searx folder. But it solves my image search issues.
