### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/searx_ynh#53]
installation fails
Could you have a look at the logs:
https://paste.yunohost.org/raw/ibolusevil
thanks for help

**Comment by AkselRocks** [comment]
I think it is related to the last upgrade https://github.com/YunoHost-Apps/searx_ynh/pull/52#issue-301818766. (was this tested also with installation and not just for upgrade?)

I once tried to upgrade, but failed and then replaced a specific folder in the searx folder with the new version and then it worked. But NOT by replacing the whole searx directory. https://github.com/YunoHost-Apps/searx_ynh/issues/51#issuecomment-508900241

**Comment by kay0u** [comment]
Hi, #52 is not in stable yet.

Could you please try to install the testing version to see if it works?

```
sudo yunohost app install https://github.com/YunoHost-Apps/searx_ynh/tree/testing --debug
```

**Comment by rocky-III** [comment]
Thanks... the testing version worked and could be installed without any problems...

**Comment by kay0u** [comment]
Nice! Thank you for your feedback!

**Comment by rocky-III** [comment]
Thanks a lot for your work kay0u..

can  you help me  with an other problem - this would be very kind as well.

I do get this kind of messages very often:

"Sorry! we didn't find any results. Please use another query or search in more categories. "

Is there a setting in:
/opt/yunohost/searx/searx/settings.yml
which I could try for better results?

**Comment by kay0u** [comment]
I think it's related to this issue:

https://github.com/asciimoo/searx/issues/1607

Unfortunately, we can't do anything until the searx team releases a new version.

**Comment by rocky-III** [comment]
Thnaks for your help
