### ISSUE TITLE
edit searx default settings

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/searx_ynh#54]
somehow the chages i mad in

/opt/yunohost/searx/searx/settings.yml

do not take effect... 
is this file the right one to edit the searx default settings?

**Comment by stemy2** [comment]
You must execute `systemctl restart uwsgi`, then your changes will take effect.

**Comment by AkselRocks** [comment]
Now its: `sudo systemctl restart uwsgi-app@searx.service`

Or restart Service in yunohost Admin Panel.

@rocky-III can this be closed?
