### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by element-i** [YunoHost-Apps/searx_ynh#55]
**Overview**

On Yunohost 3.6.5.3, Debian 9 dedicated server, searx app (version 0.15 installed from admin panel) just display "Internal server error". The yunohost configuration is standard. The installation went good.

**Log**

Seems that the issue comes from *webapp.py*, when looking at uwsgi log :
` Mon Feb 10 17:28:06 2020 - spawned uWSGI worker 4 (pid: 20778, cores: 1)
Traceback (most recent call last):
  File "/opt/yunohost/searx/searx/webapp.py", line 46, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ImportError: No module named contrib.fixers`

And then still in the same log : 
`Mon Feb 10 19:41:09 2020 - --- no python application found, check your startup logs for errors ---
[pid: 20778|app: -1|req: -1/4] 90.76.249.153 () {50 vars in 1219 bytes} [Mon Feb 10 19:41:09 2020] GET /searx/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)`

**What it should do**

Display searx home page with search bar

**What it does**

Display Internal Server Error

*Sorry if the issue is badly formated, this is my first issue reported, do not hesitate to correct me, thanks !*

**Comment by AkselRocks** [comment]
I have the same issue. 

@element-i could you find a solution/work around?

I also have an issue with peertube in the same fresh yh install. Is there maybe a connection?

**Comment by maniackcrudelis** [comment]
You can try the current testing release, https://forum.yunohost.org/t/official-app-searx/3962/10, that fix the issue while upgrading to the last version.

**Comment by AkselRocks** [comment]
installing the testing version (0.16) solved the issue for me!
sudo yunohost app install https://github.com/YunoHost-Apps/searx_ynh/tree/testing --debug
thanks @maniackcrudelis

**Comment by element-i** [comment]
That worked for me too. Thanks a lot @maniackcrudelis !
