### ISSUE TITLE
timeout?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/searx_ynh#56]
Hello,

I've always had difficulty to search with searx installed on my own server. I was always blaming my internet connection (DSL with 5-6Mbps) but now that I have a 40Mbps speed connection, it's still not working very smoothly.
I always have a lot of timeout from search engines as for example this last search: 
Google (timeout), google images (timeout), bing images (timeout), duckduckgo (timeout), yahoo (timeout), wikipedia (timeout), duckduckgo images (timeout), bing (timeout), wikidata (timeout)

Is it expected to get such result?

**Comment by maniackcrudelis** [comment]
I often have the same kind of issues with searx.
Never found a consistent workaround...

But there's actually a new version available https://github.com/asciimoo/searx/releases/tag/v0.16.0

**Comment by Thatoo** [comment]
Hopefully that will help.

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/searx_ynh/pull/57
An upgrade failed for me, but after reinstalling the app, it seems to work without errors with the search engines.
At least for now...
