### ISSUE TITLE
Error install, nginx configuration bug

### ISSUE THREAD

**Issue by magikcypress** [YunoHost-Apps/searx_ynh#8]
_error.log_
> location "ynhpanel\.(js|json|css)" cannot be inside the named location "@searx" in /etc/nginx/conf.d/yunohost_panel.conf.inc:7

**Fix**

```
--- searx.conf	2017-04-04 15:16:58.527477543 +0200
+++ searx.conf.fix	2017-04-04 15:17:21.391476652 +0200
@@ -3,6 +3,9 @@ location YNH_WWW_LOCATION {
                 rewrite ^ https://$server_name$request_uri? permanent;
         }
         try_files $uri @searx;
+
+        # Include SSOWAT user panel.
+        include conf.d/yunohost_panel.conf.inc;
 }
 
 location @searx {
@@ -11,6 +14,4 @@ location @searx {
         uwsgi_modifier1 30;
         uwsgi_pass unix:///run/uwsgi/app/searx/socket;
 
-        # Include SSOWAT user panel.
-        include conf.d/yunohost_panel.conf.inc;
 }
```

**Comment by opi** [comment]
I don't have this kind of issue, can you tell me more ?

**Comment by magikcypress** [comment]
I have this nginx error for my ynh-dev, but on my stable yunhost, i have not this problem ? 

`2017/04/05 21:52:15 [emerg] 13831#0: location "ynhpanel\.(js|json|css)" cannot be inside the named location "@searx" in /etc/nginx/conf.d/yunohost_panel.conf.inc:7
`
Because nginx don't like include into location @searx {

**Comment by TiberiusRegenschein** [comment]
I do get the same error message on my yunohost 2.6 instance with installed searx, when I try to renew my let's encrypt certificate. Only when I uninstall searx, I can renew my certificate.
Installation of searx afterwards is not possible anymore and I end up without searx on my yunohost.

**Comment by TiberiusRegenschein** [comment]
I tested with your "refactoring" branch and your latest commits. Installation was possible this time. I will keep you posted I find errors in your refactoring branch.
Thanks for solving!

**Comment by maniackcrudelis** [comment]
Fixed
