### ISSUE TITLE
Upgrade to 1.0 / Internal Server Error / No python application found

### ISSUE THREAD

**Issue by georg-mayer** [YunoHost-Apps/searx_ynh#83]
Hello,

I updated searx to version 1.0 according to the documentation here https://searx.github.io/searx/admin/update-searx.html. 

Since then I get "Internal Server Error" when trying to connect to the server.

/var/log/uwsgi/app/searx log says:

> Thu Apr  8 11:12:14 2021 - --- no python application found, check your startup logs for errors ---
> Thu Apr  8 11:12:15 2021 - --- no python application found, check your startup logs for errors ---
> Thu Apr  8 11:12:16 2021 - --- no python application found, check your startup logs for errors ---
> Thu Apr  8 11:12:21 2021 - --- no python application found, check your startup logs for errors ---

I really don't want to tweak the installation too much, as it was running perfectly before the upgrade for a long time. 

I also searched and found some posts that describe similar errors, but their fixes did not work for me. 

Any hint on possible mistakes or next steps to take would be great.

Thanks for your help!

Cheers,
Georg

**Comment by yalh76** [comment]
should be ok with last version
