### ISSUE TITLE
Feature request/Question/Bug: Reset to default settings after upgrade

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/searx_ynh#86]
### Describe the bug

after upgrade custom settings in `settings.yaml` are lost/not active.
update Warning: `File /opt/yunohost/searx/searx/settings.yml has been manually modified since the installation or last upgrade. So it has been duplicated in /home/yunohost.conf/backup//opt/yunohost/searx/searx/settings.yml.backup.20210515.075327`

### Context

- Hardware: *VPS bought online 
- YunoHost version: 4.2.4
- I have access to my server: *Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no and yes
  - If yes, please explain: see above: changes to searx settings
  - no: for YunoHost core
- Using, or trying to install package version/branch: upgrade to 1.0.0~ynh1

### Steps to reproduce

- *If you do a upgrade the instance name is reset to "YunoSearch"

### (Expected) Desired behavior

custom changes in settings stay available after upgrade.

Suggestion (if possible): Include a `custom.yaml` file in `settings.yaml`, which overwrites the default settings, but is not touched during upgrade.

### Logs

`File /opt/yunohost/searx/searx/settings.yml has been manually modified since the installation or last upgrade. So it has been duplicated in /home/yunohost.conf/backup//opt/yunohost/searx/searx/settings.yml.backup.20210515.075327`

**Comment by TROMsite** [comment]
100% agree. I always have to manually redo all settings after an upgrade.

**Comment by ericgaspar** [comment]
closing with  #91
